"""Textes d'interface du module « Banque OHP » (ligne de commande et fenêtre), FR/EN."""

TEXTES = {
    # ------------------------------------------------------------ catégories
    'ohp_cat_ast': {'fr': 'Astéroïdes', 'en': 'Asteroids'},
    'ohp_cat_neocp': {'fr': 'Désignations temporaires (NEOCP)', 'en': 'Temporary designations (NEOCP)'},
    'ohp_cat_com': {'fr': 'Comètes', 'en': 'Comets'},
    'ohp_cat_pla': {'fr': 'Planètes', 'en': 'Planets'},
    'ohp_cat_tno': {'fr': 'Transneptuniens et planètes naines', 'en': 'Trans-Neptunian objects and dwarf planets'},
    'ohp_cat_pn': {'fr': 'Nébuleuses planétaires', 'en': 'Planetary nebulae'},
    'ohp_cat_neb': {'fr': 'Nébuleuses et rémanents', 'en': 'Nebulae and remnants'},
    'ohp_cat_amas': {'fr': "Amas d'étoiles", 'en': 'Star clusters'},
    'ohp_cat_gal': {'fr': 'Galaxies', 'en': 'Galaxies'},
    'ohp_cat_eto': {'fr': 'Étoiles variables', 'en': 'Variable stars'},
    'ohp_cat_autre': {'fr': 'Non classés', 'en': 'Unclassified'},

    # ------------------------------------------------------------ ligne de commande : aides
    'ohp_meta_objet': {'fr': 'OBJET', 'en': 'OBJECT'},
    'ohp_meta_date': {'fr': 'AAAA-MM-JJ', 'en': 'YYYY-MM-DD'},
    'ohp_meta_texte': {'fr': 'TEXTE', 'en': 'TEXT'},
    'ohp_meta_mos': {'fr': 'Mo/s', 'en': 'MB/s'},
    'ohp_aide_objet': {'fr': 'objet(s) : « NGC 6888 », « Pluton », « 1998 AG6 », ou un nom de la base',
                       'en': 'object(s): « NGC 6888 », « Pluto », « 1998 AG6 », or a database name'},
    'ohp_aide_type': {'fr': 'catégorie : ast, neocp, com, pla, tno, pn, neb, amas, gal, eto (répétable)',
                      'en': 'category: ast, neocp, com, pla, tno, pn, neb, amas, gal, eto (repeatable)'},
    'ohp_aide_telescope': {'fr': 'télescope (répétable)', 'en': 'telescope (repeatable)'},
    'ohp_aide_filtre': {'fr': 'filtre : B, V, R (Johnson et Cousins), Bc, Vc, Rc, Ha, OIII, g, r, i, z, ou le nom exact '
                              '(« Johnson R ») ; répétable ou séparé par des virgules',
                        'en': 'filter: B, V, R (Johnson and Cousins), Bc, Vc, Rc, Ha, OIII, g, r, i, z, or the exact '
                              'name (« Johnson R »); repeatable or comma-separated'},
    'ohp_aide_nuit': {'fr': 'nuit (date du soir) ; répétable', 'en': 'night (evening date); repeatable'},
    'ohp_aide_dates': {'fr': 'écarte les poses à DATE-OBS partagée ou datées en plein jour',
                       'en': 'leave out exposures with a shared DATE-OBS or dated in daytime'},
    'ohp_aide_tout': {'fr': 'toute la banque (≈ 78 Go)', 'en': 'the whole bank (≈ 78 GB)'},
    'ohp_aide_rafraichir': {'fr': 'réinterroge le service TAP de l\'Observatoire (une requête)',
                            'en': "query the Observatory's TAP service again (one request)"},
    'ohp_aide_chercher': {'fr': 'filtre les objets dont le nom contient ce texte', 'en': 'keep objects whose name contains this text'},
    'ohp_aide_csv': {'fr': 'écrit aussi la liste dans ce fichier CSV', 'en': 'also write the list to this CSV file'},
    'ohp_aide_format': {'fr': 'format de sortie : xisf (PixInsight, défaut), fz (FITS compressé sans perte), fits (float32)',
                        'en': 'output format: xisf (PixInsight, default), fz (lossless compressed FITS), fits (float32)'},
    'ohp_aide_dest': {'fr': 'dossier de destination (défaut : ~/Coupole/OHP_DU_ECU ou celui des réglages)',
                      'en': 'destination folder (default: ~/Coupole/OHP_DU_ECU or the one in the settings)'},
    'ohp_aide_noms': {'fr': 'langue des noms de dossiers, d\'objets et des en-têtes (défaut : langue de l\'interface)',
                      'en': 'language of folder names, object names and headers (default: interface language)'},
    'ohp_aide_astap': {'fr': 'vérification ASTAP : auto/tous (chaque image si ASTAP est là), suspectes, jamais',
                       'en': 'ASTAP check: auto/all (every image when ASTAP is present), suspicious, never'},
    'ohp_aide_dl': {'fr': 'téléchargements simultanés (défaut automatique ; 4 au plus)',
                    'en': 'simultaneous downloads (automatic by default; at most 4)'},
    'ohp_aide_conv': {'fr': 'conversions simultanées (défaut : selon cœurs et mémoire)',
                      'en': 'simultaneous conversions (default: from cores and memory)'},
    'ohp_aide_econome': {'fr': 'mode économe : 1 conversion, 2 téléchargements', 'en': 'economy mode: 1 conversion, 2 downloads'},
    'ohp_aide_debit': {'fr': 'débit maximal vers le serveur (défaut 8 Mo/s)', 'en': 'maximum download rate (default 8 MB/s)'},
    'ohp_aide_garder': {'fr': 'garde aussi les FITS d\'origine (dans _traitement/fits_origine)',
                        'en': 'also keep the original FITS (in _traitement/fits_origine)'},
    'ohp_aide_oui': {'fr': 'accepte une sélection de plus de 5 Go sans confirmation', 'en': 'accept a selection over 5 GB without confirmation'},
    'ohp_cli_inventaire': {'fr': "état de l'inventaire ; --rafraichir l'actualise", 'en': 'inventory status; --refresh updates it'},
    'ohp_cli_inventaire_desc': {'fr': "Inventaire de la banque par le service TAP public (http://tap-ufe.obspm.fr/tap, "
                                      "table ivoa.obscore), gardé en cache local.",
                                'en': 'Bank inventory from the public TAP service (http://tap-ufe.obspm.fr/tap, table '
                                      'ivoa.obscore), kept in a local cache.'},
    'ohp_cli_catalogue': {'fr': 'catalogue des objets', 'en': 'object catalogue'},
    'ohp_cli_catalogue_desc': {'fr': 'Les 194 noms de la base regroupés en objets, classés par type.',
                               'en': 'The 194 database names grouped into objects, sorted by type.'},
    'ohp_cli_images': {'fr': "liste les images d'une sélection", 'en': 'list the images of a selection'},
    'ohp_cli_images_desc': {'fr': 'Une ligne par image : date, télescope, filtre, pose, drapeaux (doublon, date partagée, plein jour).',
                            'en': 'One line per image: date, telescope, filter, exposure, flags (duplicate, shared date, daytime).'},
    'ohp_cli_estimer': {'fr': 'volume à télécharger et place nécessaire', 'en': 'volume to download and space needed'},
    'ohp_cli_estimer_desc': {'fr': 'Estimation avant téléchargement, avec la place libre à destination.',
                             'en': 'Estimate before downloading, with the free space at the destination.'},
    'ohp_cli_traiter': {'fr': 'télécharge, vérifie, corrige, convertit et range en lots', 'en': 'download, check, fix, convert and sort into stacks'},
    'ohp_cli_traiter_desc': {'fr': "Traitement complet d'une sélection, reprenable : relancer la même commande reprend "
                                   "là où elle s'est arrêtée.",
                             'en': 'Full processing of a selection, resumable: running the same command again resumes '
                                   'where it stopped.'},
    'ohp_cli_telecharger': {'fr': 'télécharge les FITS d\'origine, sans conversion', 'en': 'download the original FITS, without conversion'},
    'ohp_cli_telecharger_desc': {'fr': 'Rangement : <dossier>/<objet>/<nuit>_<télescope>/<fichier d\'origine>.',
                                 'en': 'Layout: <folder>/<object>/<night>_<telescope>/<original file>.'},
    'ohp_cli_ranger': {'fr': 'recalcule les lots et range ce qui est converti', 'en': 'recompute the stacks and sort what is converted'},
    'ohp_cli_ranger_desc': {'fr': 'Utile après une interruption, ou pour regrouper plusieurs traitements dans un même dossier.',
                            'en': 'Useful after an interruption, or to merge several runs in the same folder.'},
    'ohp_cli_bilan': {'fr': "état d'avancement d'un dossier de traitement", 'en': 'progress of a processing folder'},

    # ------------------------------------------------------------ ligne de commande : messages
    'ohp_interrogation_tap': {'fr': 'Interrogation du service TAP de l\'Observatoire de Paris...',
                              'en': 'Querying the Observatoire de Paris TAP service...'},
    'ohp_inventaire_resume': {'fr': '{n} images ({doublons} doublons), {objets} objets, {nuits} nuits, {taille}.\n'
                                    'Inventaire du {date} — source : {source}',
                              'en': '{n} images ({doublons} duplicates), {objets} objects, {nuits} nights, {taille}.\n'
                                    'Inventory of {date} — source: {source}'},
    'ohp_col_type': {'fr': 'type', 'en': 'type'},
    'ohp_col_objet': {'fr': 'objet', 'en': 'object'},
    'ohp_col_images': {'fr': 'images', 'en': 'images'},
    'ohp_col_volume': {'fr': 'volume', 'en': 'volume'},
    'ohp_col_nuits': {'fr': 'nuits', 'en': 'nights'},
    'ohp_col_telescopes': {'fr': 'télescopes', 'en': 'telescopes'},
    'ohp_col_date': {'fr': 'date UTC', 'en': 'UTC date'},
    'ohp_col_tel': {'fr': 'tél.', 'en': 'tel.'},
    'ohp_col_filtre': {'fr': 'filtre', 'en': 'filter'},
    'ohp_col_pose': {'fr': 'pose (s)', 'en': 'exp. (s)'},
    'ohp_col_drapeaux': {'fr': 'remarques', 'en': 'flags'},
    'ohp_col_remarque': {'fr': 'remarque', 'en': 'note'},
    'ohp_col_filtres': {'fr': 'filtres', 'en': 'filters'},
    'ohp_col_noms': {'fr': 'noms dans la base', 'en': 'names in the database'},
    'ohp_catalogue_total': {'fr': '{n} objet(s).', 'en': '{n} object(s).'},
    'ohp_objet_inconnu': {'fr': 'Aucun objet ne correspond à « {q} ». Voir : coupole ohp catalogue',
                          'en': 'No object matches « {q} ». See: coupole ohp catalog'},
    'ohp_objet_ambigu': {'fr': '« {q} » correspond à plusieurs objets : {liste}. Préciser.',
                         'en': '« {q} » matches several objects: {liste}. Be more specific.'},
    'ohp_selection_vide': {'fr': 'Sélection vide : indiquer un objet, un filtre de sélection, ou --tout.',
                           'en': 'Empty selection: give an object, a selection filter, or --all.'},
    'ohp_drapeau_doublon': {'fr': 'doublon', 'en': 'duplicate'},
    'ohp_drapeau_date': {'fr': 'date partagée', 'en': 'shared date'},
    'ohp_drapeau_diurne': {'fr': 'plein jour', 'en': 'daytime'},
    'ohp_estimation': {'fr': '{images} image(s) de {objets} objet(s) sur {nuits} nuit(s) ({doublons} doublon(s) écarté(s)) : '
                             '{fits} à télécharger → environ {sortie} en {format}.',
                       'en': '{images} image(s) of {objets} object(s) over {nuits} night(s) ({doublons} duplicate(s) left '
                             'out): {fits} to download → about {sortie} as {format}.'},
    'ohp_estimation_fits': {'fr': '{images} image(s) ({doublons} doublon(s) écarté(s)) : {fits} à télécharger.',
                            'en': '{images} image(s) ({doublons} duplicate(s) left out): {fits} to download.'},
    'ohp_place': {'fr': 'Place à prévoir : {besoin} ; libre : {libre} ({dest}).', 'en': 'Space needed: {besoin}; free: {libre} ({dest}).'},
    'ohp_place_insuffisante': {'fr': 'Place insuffisante à destination.', 'en': 'Not enough space at the destination.'},
    'ohp_confirmer_gros': {'fr': 'Sélection de {taille} : ajouter --oui pour confirmer.', 'en': 'Selection of {taille}: add --yes to confirm.'},
    'ohp_rien': {'fr': 'Rien à traiter.', 'en': 'Nothing to process.'},
    'ohp_machine': {'fr': 'Machine : {cpu} cœurs ({log} logiques), {ram} Go libres → {dl} téléchargement(s), {conv} conversion(s) ({raison}).',
                    'en': 'Computer: {cpu} cores ({log} logical), {ram} GB free → {dl} download(s), {conv} conversion(s) ({raison}).'},
    'ohp_sans_astap': {'fr': "ASTAP absent : contrôles de cohérence seulement (voir « coupole astap » pour l'installer).",
                       'en': 'ASTAP missing: consistency checks only (see « coupole astap » to install it).'},
    'ohp_astap_desactive': {'fr': 'ASTAP désactivé : contrôles de cohérence seulement.', 'en': 'ASTAP disabled: consistency checks only.'},
    'ohp_avec_astap': {'fr': 'ASTAP : {exe} (catalogue {cat}).', 'en': 'ASTAP: {exe} (catalogue {cat}).'},
    'ohp_debut': {'fr': '{total} image(s) à traiter ({deja} déjà faite(s)).', 'en': '{total} image(s) to process ({deja} already done).'},
    'ohp_ligne_image': {'fr': '[{n}/{total}] {statut:9} {wcs:11} {debit} Mo/s  {source}',
                        'en': '[{n}/{total}] {statut:9} {wcs:11} {debit} MB/s  {source}'},
    'ohp_ligne_echec': {'fr': 'ÉCHEC {source} : {erreur}', 'en': 'FAILED {source}: {erreur}'},
    'ohp_statut_ok': {'fr': 'converti', 'en': 'converted'},
    'ohp_statut_doublon': {'fr': 'doublon', 'en': 'duplicate'},
    'ohp_statut_echec': {'fr': 'échec', 'en': 'failed'},
    'ohp_wcs_confirmee': {'fr': 'confirmée', 'en': 'confirmed'},
    'ohp_wcs_validee': {'fr': 'validée', 'en': 'validated'},
    'ohp_wcs_refaite': {'fr': 'refaite', 'en': 'redone'},
    'ohp_wcs_echec': {'fr': 'sans solution', 'en': 'no solution'},
    'ohp_wcs_douteuse': {'fr': 'douteuse', 'en': 'doubtful'},
    'ohp_wcs_aucune': {'fr': '—', 'en': '—'},
    'ohp_bilan': {'fr': '{ok} converties, {doublons} doublons, {echecs} échecs ; {fits} de FITS → {sortie} ({ratio} %) ; '
                        '{lots} lots dans {dest}',
                  'en': '{ok} converted, {doublons} duplicates, {echecs} failures; {fits} of FITS → {sortie} ({ratio} %); '
                        '{lots} stacks in {dest}'},
    'ohp_bilan_wcs': {'fr': 'Solutions astrométriques : {v}', 'en': 'Astrometric solutions: {v}'},
    'ohp_relancer': {'fr': 'Des échecs : relancer la même commande (reprise automatique, 5 essais par image).',
                     'en': 'Some failures: run the same command again (automatic resume, 5 attempts per image).'},
    'ohp_ranges': {'fr': '{n} lot(s) rangé(s).', 'en': '{n} stack(s) sorted.'},
    'ohp_pas_de_traitement': {'fr': 'Aucun traitement dans {dest}.', 'en': 'No processing in {dest}.'},
    'ohp_dl_ok': {'fr': 'téléchargé', 'en': 'downloaded'},
    'ohp_dl_deja': {'fr': 'déjà là  ', 'en': 'present   '},
    'ohp_dl_echec': {'fr': 'ÉCHEC    ', 'en': 'FAILED    '},
    'ohp_dl_fin': {'fr': '{n} fichier(s) dans {dest}, {echecs} échec(s).', 'en': '{n} file(s) in {dest}, {echecs} failure(s).'},
    'ohp_avis_langue_impose': {'fr': 'Ce dossier a déjà été traité avec les noms en « {valeur} » : cette langue est gardée.',
                               'en': 'This folder was already processed with names in « {valeur} »: that language is kept.'},
    'ohp_avis_format_impose': {'fr': 'Ce dossier a déjà été traité au format « {valeur} » : ce format est gardé.',
                               'en': 'This folder was already processed in « {valeur} » format: that format is kept.'},
# ------------------------------------------------------------ doublons, anomalies, classement
    'ohp_aide_garder_doublons': {'fr': "traite aussi les doublons (inventaire et pixels identiques) au lieu de les écarter",
                                 'en': 'also process duplicates (inventory and identical pixels) instead of leaving them out'},
    'ohp_url_injoignable': {'fr': "si l'adresse de téléchargement ne répond plus, voir Préférences > Sources (ou « coupole sources »)",
                            'en': 'if the download address no longer answers, see Preferences > Sources (or « coupole sources »)'},
    'ohp_cli_anomalies': {'fr': "rapport d'anomalies : ce qui est écarté ou signalé, et pourquoi", 'en': 'anomaly report: what is left out or flagged, and why'},
    'ohp_cli_anomalies_desc': {'fr': "Doublons (même fichier, copie diurne, pixels identiques), dates partagées ou diurnes, champ incohérent, "
                                     "classement à vérifier, instrument inconnu. Rien n'est supprimé.",
                               'en': 'Duplicates (same file, daytime copy, identical pixels), shared or daytime dates, inconsistent field, '
                                     'classification to check, unknown instrument. Nothing is deleted.'},
    'ohp_aide_dest_anomalies': {'fr': 'ajoute les doublons de pixels trouvés dans ce dossier de traitement',
                                'en': 'add the pixel duplicates found in this processing folder'},
    'ohp_aide_nouveaux': {'fr': 'seulement les images nouvelles depuis le dernier rafraîchissement', 'en': 'only images new since the last refresh'},
    'ohp_cli_classer': {'fr': 'classement des noms de cibles : vérifier, corriger, fusionner', 'en': 'target name classification: check, correct, merge'},
    'ohp_cli_classer_desc': {'fr': "Sans argument : liste les noms à vérifier. Avec un nom de la base et --objet : mémorise la correction "
                                   "(fusion avec un objet existant si --type est omis). --en-ligne : interroge JPL SBDB et CDS Sesame.",
                             'en': 'Without argument: list the names to check. With a database name and --object: record the correction '
                                   '(merge into an existing object if --type is omitted). --online: query JPL SBDB and CDS Sesame.'},
    'ohp_meta_nom_base': {'fr': 'NOM_BASE', 'en': 'DB_NAME'},
    'ohp_aide_nom_base': {'fr': 'nom de cible tel qu\'il figure dans la base', 'en': 'target name as it appears in the database'},
    'ohp_aide_classer_objet': {'fr': 'objet canonique à associer (existant : fusion)', 'en': 'canonical object to associate (existing one: merge)'},
    'ohp_aide_classer_oublier': {'fr': 'oublie la correction de ce nom', 'en': 'forget the correction of this name'},
    'ohp_aide_en_ligne': {'fr': 'résout en ligne les noms inconnus (JPL SBDB, CDS Sesame), avec cache', 'en': 'resolve unknown names online (JPL SBDB, CDS Sesame), with cache'},
    'ohp_nouveautes': {'fr': '{images} image(s) et {noms} nom(s) de cible nouveaux depuis le {depuis} :',
                       'en': '{images} new image(s) and {noms} new target name(s) since {depuis}:'},
    'ohp_classement_utilisateur': {'fr': '(corrigé par vous)', 'en': '(corrected by you)'},
    'ohp_classement_distant': {'fr': '(table publiée)', 'en': '(published table)'},
    'ohp_classement_table': {'fr': '(table vérifiée)', 'en': '(checked table)'},
    'ohp_classement_regle': {'fr': '(règle sur le nom)', 'en': '(name rule)'},
    'ohp_classement_sbdb': {'fr': '(JPL SBDB, à vérifier)', 'en': '(JPL SBDB, to check)'},
    'ohp_classement_sesame': {'fr': '(CDS Sesame, à vérifier)', 'en': '(CDS Sesame, to check)'},
    'ohp_classement_en_ligne': {'fr': '(en ligne, à vérifier)', 'en': '(online, to check)'},
    'ohp_classement_position': {'fr': '(même champ qu\'un objet connu, à vérifier)', 'en': '(same field as a known object, to check)'},
    'ohp_classement_inconnu': {'fr': '(non classé, à vérifier)', 'en': '(unclassified, to check)'},
    'ohp_anomalies_total': {'fr': '{n} anomalie(s). Rien n\'a été supprimé ; « garder les doublons » traite aussi ce qui est écarté.',
                            'en': '{n} anomaly(ies). Nothing was deleted; « keep duplicates » also processes what is left out.'},
    'ohp_resolution': {'fr': 'Résolution en ligne de {n} nom(s) inconnu(s)...', 'en': 'Resolving {n} unknown name(s) online...'},
    'ohp_a_verifier': {'fr': '{n} nom(s) à vérifier.', 'en': '{n} name(s) to check.'},
    'ohp_correction_oubliee': {'fr': 'Correction de « {nom} » oubliée.', 'en': 'Correction of « {nom} » forgotten.'},
    'ohp_nom_absent': {'fr': '« {nom} » ne figure pas dans la base.', 'en': '« {nom} » is not in the database.'},
    'ohp_correction_faite': {'fr': '« {nom} » → {objet} [{cat}] : correction mémorisée.', 'en': '« {nom} » → {objet} [{cat}]: correction recorded.'},
    'anom_action_ecartee': {'fr': 'écartée', 'en': 'left out'},
    'anom_action_signalee': {'fr': 'signalée', 'en': 'flagged'},
    'anom_meme_fichier': {'fr': 'même pose sous un autre chemin ou une autre orthographe', 'en': 'same exposure under another path or spelling'},
    'anom_copie_diurne': {'fr': "copie datée en plein jour d'une image bien datée", 'en': 'daytime-dated copy of a correctly dated image'},
    'anom_memes_meta': {'fr': 'mêmes date, filtre, pose et taille qu\'une autre image (nom différent)', 'en': 'same date, filter, exposure and size as another image (different name)'},
    'anom_date_partagee': {'fr': 'DATE-OBS identique à celle d\'une autre pose (une des deux est fausse)', 'en': 'DATE-OBS identical to another exposure (one of them is wrong)'},
    'anom_date_diurne': {'fr': 'pose datée entre 5 h et 17 h UTC', 'en': 'exposure dated between 5 and 17 h UTC'},
    'anom_champ_incoherent': {'fr': 'centre du champ loin des autres poses de l\'objet', 'en': 'field centre far from the other exposures of the object'},
    'anom_classement': {'fr': 'nom classé automatiquement ou non classé : à vérifier', 'en': 'name classified automatically or not at all: to check'},
    'anom_instrument': {'fr': 'instrument inconnu de la table (rangé à part)', 'en': 'instrument unknown to the table (kept separate)'},
    'anom_pixels_identiques': {'fr': 'pixels identiques à une autre image (empreinte SHA-1)', 'en': 'pixels identical to another image (SHA-1 fingerprint)'},
    'anom_col_genre': {'fr': 'anomalie', 'en': 'anomaly'},
    'anom_col_action': {'fr': 'action', 'en': 'action'},
    'anom_col_objet': {'fr': 'objet', 'en': 'object'},
    'anom_col_nuit': {'fr': 'nuit', 'en': 'night'},
    'anom_col_fichier': {'fr': 'fichier', 'en': 'file'},
    'anom_col_detail': {'fr': 'détail', 'en': 'detail'},
    'anom_col_explication': {'fr': 'explication', 'en': 'explanation'},
    'anom_col_url': {'fr': 'adresse', 'en': 'address'},
# ------------------------------------------------------------ interface graphique
    'ohp_onglets_aide': {'fr': 'Catalogue → Traitement → Lots ; Anomalies : ce qui est écarté et pourquoi.',
                         'en': 'Catalogue → Processing → Stacks; Anomalies: what is left out and why.'},
    'ohp_onglet_catalogue': {'fr': 'Catalogue', 'en': 'Catalogue'},
    'ohp_onglet_traitement': {'fr': 'Traitement', 'en': 'Processing'},
    'ohp_onglet_lots': {'fr': 'Lots', 'en': 'Stacks'},
    'ohp_onglet_anomalies': {'fr': 'Anomalies', 'en': 'Anomalies'},
    'ohp_recherche_aide': {'fr': "Filtre les objets par nom (objet canonique ou nom de la base).", 'en': 'Filter objects by name (canonical object or database name).'},
    'ohp_recherche_indice': {'fr': 'Chercher un objet (NGC 6888, Pluton, 1998 AG6…)', 'en': 'Search an object (NGC 6888, Pluto, 1998 AG6…)'},
    'ohp_f_cat_aide': {'fr': "Type d'objet.", 'en': 'Object type.'},
    'ohp_f_tel_aide': {'fr': 'Télescope : T120 (1,20 m) ou IRIS (50 cm).', 'en': 'Telescope: T120 (1.20 m) or IRIS (50 cm).'},
    'ohp_tous_types': {'fr': 'Tous les types', 'en': 'All types'},
    'ohp_tous_tel': {'fr': 'Tous les télescopes', 'en': 'All telescopes'},
    'ohp_toutes_nuits': {'fr': 'Toutes les nuits', 'en': 'All nights'},
    'ohp_tous_filtres': {'fr': 'Tous les filtres', 'en': 'All filters'},
    'ohp_tous_genres': {'fr': 'Toutes les anomalies', 'en': 'All anomalies'},
    'ohp_f_nouveaux': {'fr': 'Nouveaux seulement', 'en': 'New only'},
    'ohp_f_nouveaux_aide': {'fr': "Seulement ce qui est apparu depuis le rafraîchissement précédent de l'inventaire.",
                            'en': 'Only what appeared since the previous inventory refresh.'},
    'ohp_f_verifier': {'fr': 'À vérifier', 'en': 'To check'},
    'ohp_f_verifier_aide': {'fr': 'Seulement les objets classés automatiquement ou non classés.', 'en': 'Only objects classified automatically or not at all.'},
    'ohp_f_nuit_aide': {'fr': 'Nuit (date du soir, heure UTC moins 12 h).', 'en': 'Night (evening date, UTC minus 12 h).'},
    'ohp_f_filtre_aide': {'fr': 'Filtre tel que nommé dans la base.', 'en': 'Filter as named in the database.'},
    'ohp_f_dates': {'fr': 'Sans dates douteuses', 'en': 'Without doubtful dates'},
    'ohp_f_dates_aide': {'fr': 'Écarte les poses à DATE-OBS partagée ou datées en plein jour (utile pour CometAlignment et la photométrie datée).',
                         'en': 'Leave out exposures with a shared DATE-OBS or dated in daytime (useful for CometAlignment and timed photometry).'},
    'ohp_f_genre_aide': {'fr': "Genre d'anomalie.", 'en': 'Kind of anomaly.'},
    'ohp_rafraichir': {'fr': "Rafraîchir l'inventaire", 'en': 'Refresh the inventory'},
    'ohp_rafraichir_aide': {'fr': "Réinterroge le service TAP de l'Observatoire (une requête, quelques secondes) et montre ce qui est nouveau (Ctrl+R).",
                            'en': "Query the Observatory's TAP service again (one request, a few seconds) and show what is new (Ctrl+R)."},
    'ohp_chargement': {'fr': "Chargement de l'inventaire…", 'en': 'Loading the inventory…'},
    'ohp_inventaire_erreur': {'fr': "Inventaire indisponible : {erreur}. L'inventaire en cache (ou livré) reste utilisable ; voir Préférences > Sources.",
                              'en': 'Inventory unavailable: {erreur}. The cached (or shipped) inventory is still usable; see Preferences > Sources.'},
    'ohp_table_objets_aide': {'fr': 'Objets de la banque. Sélectionner un ou plusieurs objets pour voir leurs images (Ctrl/Maj pour plusieurs).',
                              'en': 'Objects of the bank. Select one or several objects to see their images (Ctrl/Shift for several).'},
    'ohp_table_images_aide': {'fr': "Images des objets sélectionnés : c'est la sélection qui sera traitée.",
                              'en': 'Images of the selected objects: this is the selection that will be processed.'},
    'ohp_col_etat': {'fr': 'état', 'en': 'status'},
    'ohp_col_nuit': {'fr': 'nuit', 'en': 'night'},
    'ohp_etat_nouveau': {'fr': 'nouveau ({date})', 'en': 'new ({date})'},
    'ohp_etat_verifier': {'fr': 'à vérifier', 'en': 'to check'},
    'ohp_bulle_objet': {'fr': 'Noms dans la base : {noms} — doublons écartés : {doublons}', 'en': 'Names in the database: {noms} — duplicates left out: {doublons}'},
    'ohp_aucune_selection': {'fr': 'Aucune image sélectionnée : choisir un objet dans le catalogue.', 'en': 'No image selected: pick an object in the catalogue.'},
    'ohp_libre': {'fr': 'Libre à destination : {libre}.', 'en': 'Free at destination: {libre}.'},
    'ohp_corriger': {'fr': 'Corriger le classement…', 'en': 'Correct the classification…'},
    'ohp_corriger_aide': {'fr': "Renommer l'objet, changer son type, ou le fusionner avec un autre (correction mémorisée).",
                          'en': 'Rename the object, change its type, or merge it into another (correction recorded).'},
    'ohp_corriger_un': {'fr': 'Sélectionner un seul objet.', 'en': 'Select a single object.'},
    'ohp_corriger_texte': {'fr': 'Objet : {objet}\nNoms dans la base : {noms}', 'en': 'Object: {objet}\nNames in the database: {noms}'},
    'ohp_corr_nom': {'fr': 'Nom canonique', 'en': 'Canonical name'},
    'ohp_corr_nom_aide': {'fr': 'Nom utilisé pour les dossiers, OBJECT et les lots.', 'en': 'Name used for folders, OBJECT and stacks.'},
    'ohp_corr_cat': {'fr': 'Type', 'en': 'Type'},
    'ohp_corr_cat_aide': {'fr': 'Détermine le tri : par champ (objets fixes) ou par nuit (objets mobiles).', 'en': 'Decides the sorting: by field (fixed objects) or by night (moving objects).'},
    'ohp_corr_fusion': {'fr': 'Fusionner avec', 'en': 'Merge into'},
    'ohp_corr_fusion_aide': {'fr': "Ces noms sont un alias d'un objet existant.", 'en': 'These names are an alias of an existing object.'},
    'ohp_corr_pas_fusion': {'fr': '(pas de fusion)', 'en': '(no merge)'},
    'ohp_corr_oublier': {'fr': 'Oublier ma correction', 'en': 'Forget my correction'},
    'ohp_corr_oublier_aide': {'fr': 'Revenir au classement automatique.', 'en': 'Go back to automatic classification.'},
    'ohp_corr_enregistrer': {'fr': 'Enregistrer', 'en': 'Save'},
    'ohp_corr_enregistrer_aide': {'fr': 'Mémorise la correction (fichier ohp_corrections.json des réglages).', 'en': 'Record the correction (ohp_corrections.json in the settings).'},
    'ohp_vers_traitement': {'fr': 'Traiter cette sélection →', 'en': 'Process this selection →'},
    'ohp_vers_traitement_aide': {'fr': "Passe à l'onglet Traitement avec les images listées à droite.", 'en': 'Go to the Processing tab with the images listed on the right.'},
    'ohp_selection_courante': {'fr': 'Sélection : {n} image(s) — {objets}', 'en': 'Selection: {n} image(s) — {objets}'},
    'ohp_groupe_sortie': {'fr': 'Sortie', 'en': 'Output'},
    'ohp_groupe_astrometrie': {'fr': 'Solution astrométrique', 'en': 'Astrometric solution'},
    'ohp_groupe_machine': {'fr': 'Machine et réseau', 'en': 'Computer and network'},
    'ohp_dest_aide': {'fr': 'Dossier de destination ; un dossier déjà traité est complété et repris, jamais écrasé.',
                      'en': 'Destination folder; a folder already processed is completed and resumed, never overwritten.'},
    'ohp_garder_doublons': {'fr': 'Garder les doublons', 'en': 'Keep duplicates'},
    'ohp_garder_doublons_aide': {'fr': "Traite aussi les doublons de l'inventaire et les pixels identiques (signalés dans le journal).",
                                 'en': 'Also process inventory duplicates and identical pixels (flagged in the log).'},
    'ohp_garder_fits': {'fr': "Garder les FITS d'origine", 'en': 'Keep the original FITS'},
    'ohp_garder_fits_aide': {'fr': "Conserve aussi les fichiers téléchargés (dans _traitement/fits_origine) : place doublée.",
                             'en': 'Also keep the downloaded files (in _traitement/fits_origine): double the space.'},
    'ohp_mode_astap_aide': {'fr': "Quand vérifier avec ASTAP : chaque image, seulement les solutions douteuses, ou jamais.",
                            'en': 'When to check with ASTAP: every image, only doubtful solutions, or never.'},
    'ohp_astap_tous': {'fr': 'Vérifier chaque image', 'en': 'Check every image'},
    'ohp_astap_suspectes': {'fr': 'Seulement les douteuses', 'en': 'Doubtful ones only'},
    'ohp_astap_jamais': {'fr': 'Jamais', 'en': 'Never'},
    'ohp_assistant_astap': {'fr': 'Assistant ASTAP…', 'en': 'ASTAP assistant…'},
    'ohp_assistant_astap_aide': {'fr': 'Détecter ou installer ASTAP (facultatif).', 'en': 'Detect or install ASTAP (optional).'},
    'ohp_lancer': {'fr': 'Lancer', 'en': 'Start'},
    'ohp_lancer_aide': {'fr': "Télécharge, vérifie, corrige, convertit et range la sélection. Reprenable à tout moment.",
                        'en': 'Download, check, fix, convert and sort the selection. Resumable at any time.'},
    'ohp_arreter': {'fr': 'Arrêter', 'en': 'Stop'},
    'ohp_arreter_aide': {'fr': "Arrête proprement : les images en cours se terminent, la reprise repart de là.",
                         'en': 'Stop cleanly: images in progress finish, resuming starts from there.'},
    'ohp_barre_aide': {'fr': 'Images traitées sur le total.', 'en': 'Images processed out of the total.'},
    'ohp_journal_aide': {'fr': 'Journal du traitement (le détail complet est dans _traitement/journal.csv).',
                         'en': 'Processing log (full details in _traitement/journal.csv).'},
    'ohp_journal_debut': {'fr': '{n} image(s) → {dest} ({format}).', 'en': '{n} image(s) → {dest} ({format}).'},
    'ohp_arret_demande': {'fr': 'Arrêt demandé : fin des images en cours…', 'en': 'Stop requested: finishing images in progress…'},
    'ohp_stats': {'fr': 'Débit : {debit} Mo/s — reste environ {reste} min', 'en': 'Rate: {debit} MB/s — about {reste} min left'},
    'ohp_erreur_traitement': {'fr': 'Erreur : {erreur} (rapportée ; relancer reprend le traitement).', 'en': 'Error: {erreur} (reported; starting again resumes processing).'},
    'ohp_confirmer_gros_gui': {'fr': 'La sélection fait {taille}. Continuer ?', 'en': 'The selection is {taille}. Continue?'},
    'ohp_lots_actualiser': {'fr': 'Actualiser', 'en': 'Refresh'},
    'ohp_lots_actualiser_aide': {'fr': 'Relit INDEX_LOTS.csv du dossier de sortie.', 'en': 'Read INDEX_LOTS.csv of the output folder again.'},
    'ohp_lots_ouvrir': {'fr': 'Ouvrir la fiche du lot', 'en': 'Open the stack sheet'},
    'ohp_lots_ouvrir_aide': {'fr': 'Ouvre LOT.txt (objet, poses, nuits, conseil d\'empilement). Double-clic : idem.',
                             'en': 'Open LOT.txt (object, exposures, nights, stacking advice). Double-click: same.'},
    'ohp_lots_dossier': {'fr': 'Ouvrir le dossier', 'en': 'Open the folder'},
    'ohp_lots_dossier_aide': {'fr': 'Ouvre le dossier de sortie dans le gestionnaire de fichiers.', 'en': 'Open the output folder in the file manager.'},
    'ohp_table_lots_aide': {'fr': 'Un lot = ce qu\'on empile ensemble (même objet, instrument, filtre, et même champ ou même nuit).',
                            'en': 'A stack = what is stacked together (same object, instrument, filter, and same field or same night).'},
    'ohp_lots_resume': {'fr': '{n} lot(s) dans {dest}', 'en': '{n} stack(s) in {dest}'},
    'ohp_lots_aucun': {'fr': 'Aucun lot dans {dest} pour le moment.', 'en': 'No stack in {dest} yet.'},
    'ohp_anomalies_intro': {'fr': "Ce qui est écarté ou signalé, et pourquoi. Rien n'est supprimé ; « Garder les doublons » traite aussi ce qui est écarté.",
                            'en': "What is left out or flagged, and why. Nothing is deleted; « Keep duplicates » also processes what is left out."},
    'ohp_table_anom_aide': {'fr': "Une ligne par image et par anomalie ; survol : adresse de l'image.", 'en': 'One line per image and anomaly; hover: image address.'},
    'ohp_anom_csv': {'fr': 'Exporter en CSV…', 'en': 'Export as CSV…'},
    'ohp_anom_csv_aide': {'fr': "Enregistre le rapport d'anomalies (colonnes bilingues).", 'en': 'Save the anomaly report (bilingual columns).'},
    'ohp_aide_html': {
        'fr': "<h3>Banque OHP</h3><p>Images des stages du DU à l'Observatoire de Haute-Provence (T120 depuis 2015, IRIS depuis "
              "2021), déjà calibrées (dark, flat) et résolues astrométriquement par la base.</p>"
              "<h4>Catalogue</h4><p>Les noms de la base sont regroupés en objets. Sélectionner des objets, filtrer nuit et "
              "filtre à droite : la liste de droite est la sélection. Volume estimé en bas. <b>Ne pas recalibrer</b> ces "
              "images.</p><h4>Traitement</h4><p>Pour chaque image : téléchargement (reprise, contrôle de taille et d'en-tête), "
              "contrôle de la solution astrométrique (cohérence ; ASTAP s'il est installé), en-tête corrigé (objet, filtre, "
              "site MPC 511, centre réel, échelle, angle ; anciennes valeurs en HISTORY), conversion vérifiée pixel à pixel, "
              "rangement en lots. Arrêter puis relancer reprend là où c'était.</p><h4>Lots</h4><p>Objets fixes : un lot par "
              "champ (toutes nuits) et par filtre → StarAlignment. Objets mobiles : un lot par nuit → CometAlignment. "
              "LOT.txt donne le conseil d'empilement.</p><h4>Anomalies</h4><p>Doublons, dates partagées ou diurnes, champs "
              "incohérents, noms à vérifier : tout est expliqué, rien n'est supprimé.</p>",
        'en': "<h3>OHP image bank</h3><p>Images from the diploma's training nights at the Observatoire de Haute-Provence "
              "(T120 since 2015, IRIS since 2021), already calibrated (dark, flat) and astrometrically solved by the database.</p>"
              "<h4>Catalogue</h4><p>Database names are grouped into objects. Select objects, filter night and filter on the "
              "right: the right-hand list is the selection. Estimated volume at the bottom. <b>Do not recalibrate</b> these "
              "images.</p><h4>Processing</h4><p>For each image: download (resume, size and header checks), astrometric "
              "solution check (consistency; ASTAP if installed), fixed header (object, filter, MPC 511 site, true centre, "
              "scale, angle; old values in HISTORY), conversion checked pixel by pixel, sorting into stacks. Stopping then "
              "starting again resumes where it was.</p><h4>Stacks</h4><p>Fixed objects: one stack per field (all nights) and "
              "filter → StarAlignment. Moving objects: one stack per night → CometAlignment. LOT.txt gives stacking advice.</p>"
              "<h4>Anomalies</h4><p>Duplicates, shared or daytime dates, inconsistent fields, names to check: everything is "
              "explained, nothing is deleted.</p>"},
'ohp_onglet_ciel': {'fr': 'Carte du ciel', 'en': 'Sky map'},
    'ohp_ciel_intro': {'fr': 'Un point par objet fixe (taille : nombre d\'images), un point par nuit pour les objets mobiles. Clic : sélectionne l\'objet.',
                       'en': 'One point per fixed object (size: number of images), one point per night for moving objects. Click: select the object.'},
    'ohp_ciel_aide': {'fr': 'Survol : nom et nombre d\'images ; clic : ouvre l\'objet dans le catalogue.', 'en': 'Hover: name and number of images; click: open the object in the catalogue.'},
    'ohp_ciel_bulle': {'fr': '{nom}\n{cat} — {n} image(s)', 'en': '{nom}\n{cat} — {n} image(s)'},
    'ohp_col_heure_site': {'fr': 'heure du site', 'en': 'site time'},
'ohp_meta_cat': {'fr': 'TYPE', 'en': 'TYPE'},
'ohp_qualite': {'fr': 'Vérifier la qualité des images', 'en': 'Check image quality'},
    'ohp_qualite_aide': {'fr': 'Facultatif : après le traitement, mesure chaque lot (QUALITE.csv, QUALITE.txt). Demande SEP.',
                         'en': 'Optional: after processing, measure each stack (QUALITE.csv, QUALITE.txt). Needs SEP.'},
}
